kind: pipeline
type: docker
name: 文件传输


clone:
  disable: true


environment:
  VERSION: 0.0.1
  GO: lang/go
  JAVA: lang/java


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: dronestock/protobuf
    settings:
      outputs:
        - go => $${GO}
        - java => $${JAVA}
      opts:
        - go => module=github.com/storezhang/transfer

  - name: Golang
    image: dronestock/git
    settings:
      remote: git@github.com:storezhang/transfer.git
      folder: $${GO}
      commit: ${DRONE_COMMIT_MESSAGE}
      tag: v$${VERSION}
      ssh_key:
        from_secret: ssh_key_github

  - name: Java
    image: dronestock/maven
    settings:
      folder: $${JAVA}
      version: $${VERSION}
