// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: storezhang/transfer/oss.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 阿里云对象存储
type Oss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 通信地址
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// 基础路径
	Base string `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	// 授权，相当于用户名
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// 授权，相当于密码
	Key string `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	// 临时密钥
	Token string `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	// 分隔符
	// gotags: default:"/"
	Separator string `protobuf:"bytes,8,opt,name=separator,proto3" json:"separator,omitempty"`
}

func (x *Oss) Reset() {
	*x = Oss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storezhang_transfer_oss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oss) ProtoMessage() {}

func (x *Oss) ProtoReflect() protoreflect.Message {
	mi := &file_storezhang_transfer_oss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oss.ProtoReflect.Descriptor instead.
func (*Oss) Descriptor() ([]byte, []int) {
	return file_storezhang_transfer_oss_proto_rawDescGZIP(), []int{0}
}

func (x *Oss) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Oss) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Oss) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Oss) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Oss) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Oss) GetSeparator() string {
	if x != nil {
		return x.Separator
	}
	return ""
}

var File_storezhang_transfer_oss_proto protoreflect.FileDescriptor

var file_storezhang_transfer_oss_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f, 0x6f, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x03, 0x4f, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x42, 0x45, 0x0a, 0x18, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x01,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x3b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_storezhang_transfer_oss_proto_rawDescOnce sync.Once
	file_storezhang_transfer_oss_proto_rawDescData = file_storezhang_transfer_oss_proto_rawDesc
)

func file_storezhang_transfer_oss_proto_rawDescGZIP() []byte {
	file_storezhang_transfer_oss_proto_rawDescOnce.Do(func() {
		file_storezhang_transfer_oss_proto_rawDescData = protoimpl.X.CompressGZIP(file_storezhang_transfer_oss_proto_rawDescData)
	})
	return file_storezhang_transfer_oss_proto_rawDescData
}

var file_storezhang_transfer_oss_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storezhang_transfer_oss_proto_goTypes = []interface{}{
	(*Oss)(nil), // 0: storezhang.transfer.Oss
}
var file_storezhang_transfer_oss_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storezhang_transfer_oss_proto_init() }
func file_storezhang_transfer_oss_proto_init() {
	if File_storezhang_transfer_oss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storezhang_transfer_oss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storezhang_transfer_oss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storezhang_transfer_oss_proto_goTypes,
		DependencyIndexes: file_storezhang_transfer_oss_proto_depIdxs,
		MessageInfos:      file_storezhang_transfer_oss_proto_msgTypes,
	}.Build()
	File_storezhang_transfer_oss_proto = out.File
	file_storezhang_transfer_oss_proto_rawDesc = nil
	file_storezhang_transfer_oss_proto_goTypes = nil
	file_storezhang_transfer_oss_proto_depIdxs = nil
}
